services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  AsyncExportBundle\Repository\:
    resource: '../../Repository/'

  AsyncExportBundle\Controller\Admin\:
    resource: '../../Controller/Admin/'

  AsyncExportBundle\Service\:
    resource: '../../Service/'

  AsyncExportBundle\Command\:
    resource: '../../Command/'

  # 异步导出服务配置
  AsyncExportBundle\Service\AsyncExportService:
    arguments:
      $projectDir: '%kernel.project_dir%'

  AsyncExportBundle\Service\ExportFileService:
    arguments:
      $projectDir: '%kernel.project_dir%'
